
package com.kan.webservice.getmsg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Function", targetNamespace = "http://function.kan.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Function {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.kan.getmsg.Message
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pingIp", targetNamespace = "http://function.kan.com/", className = "com.kan.getmsg.PingIp")
    @ResponseWrapper(localName = "pingIpResponse", targetNamespace = "http://function.kan.com/", className = "com.kan.getmsg.PingIpResponse")
    @Action(input = "http://function.kan.com/Function/pingIpRequest", output = "http://function.kan.com/Function/pingIpResponse")
    public Message pingIp(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transWords", targetNamespace = "http://function.kan.com/", className = "com.kan.getmsg.TransWords")
    @ResponseWrapper(localName = "transWordsResponse", targetNamespace = "http://function.kan.com/", className = "com.kan.getmsg.TransWordsResponse")
    @Action(input = "http://function.kan.com/Function/transWordsRequest", output = "http://function.kan.com/Function/transWordsResponse")
    public String transWords(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
